const constants = {
    TASK_REORDER_START: `TASK_REORDER_START`,
    TASK_REORDER_SUCCESS: `TASK_REORDER_SUCCESS`,
    TASK_REORDER_ERROR: `TASK_REORDER_ERROR`,

    TASK_ON_SELECT: `TASK_ON_SELECT`,
    TASK_FIND_START: `TASK_FIND_START`,
    TASK_FIND_SUCCESS: `TASK_FIND_SUCCESS`,
    TASK_FIND_ERROR: `TASK_FIND_ERROR`,

    TASK_UPDATE_START: `TASK_UPDATE_START`,
    TASK_UPDATE_SUCCESS: `TASK_UPDATE_SUCCESS`,
    TASK_UPDATE_ERROR: `TASK_UPDATE_ERROR`,

    TASK_DESTROY_START: `TASK_DESTROY_START`,
    TASK_DESTROY_SUCCESS: `TASK_DESTROY_SUCCESS`,
    TASK_DESTROY_ERROR: `TASK_DESTROY_ERROR`,

    TASK_DESTROY_FILE_START: `TASK_DESTROY_FILE_START`,
    TASK_DESTROY_FILE_SUCCESS: `TASK_DESTROY_FILE_SUCCESS`,
    TASK_DESTROY_FILE_ERROR: `TASK_DESTROY_FILE_ERROR`,

    INPUT_FILE_LIST_CHANGE: `INPUT_FILE_LIST_CHANGE`,
    INPUT_IMAGE_LIST_CHANGE: `INPUT_IMAGE_LIST_CHANGE`,

    TASK_GET_IMAGE_LIST_START: `TASK_GET_IMAGE_LIST_START`,
    TASK_GET_IMAGE_LIST_SUCCESS: `TASK_GET_IMAGE_LIST_SUCCESS`,
    TASK_GET_IMAGE_LIST_ERROR: `TASK_GET_IMAGE_LIST_ERROR`,

    TASK_GET_FILE_LIST_START: `TASK_GET_FILE_LIST_START`,
    TASK_GET_FILE_LIST_SUCCESS: `TASK_GET_FILE_LIST_SUCCESS`,
    TASK_GET_FILE_LIST_ERROR: `TASK_GET_FILE_LIST_ERROR`,

    TASK_GET_COMMENT_START: `TASK_GET_COMMENT_START`,
    TASK_GET_COMMENT_SUCCESS: `TASK_GET_COMMENT_SUCCESS`,
    TASK_GET_COMMENT_ERROR: `TASK_GET_COMMENT_ERROR`,

    TASK_LIST_COMMENT_CHANGE: `TASK_LIST_COMMENT_CHANGE`,

    TASK_DESTROY_COMMENT_START: `TASK_DESTROY_COMMENT_START`,
    TASK_DESTROY_COMMENT_SUCCESS: `TASK_DESTROY_COMMENT_SUCCESS`,
    TASK_DESTROY_COMMENT_ERROR: `TASK_DESTROY_COMMENT_ERROR`,
};
export default constants;
