const constants = {
    USER_FIND_START : `USER_FIND_START`,
    USER_FIND_SUCCESS : `USER_FIND_SUCCESS`,
    USER_FIND_ERROR : `USER_FIND_ERROR`,

    USER_UPDATE_START : `USER_UPDATE_START`,
    USER_UPDATE_SUCCESS : `USER_UPDATE_SUCCESS`,
    USER_UPDATE_ERROR : `USER_UPDATE_ERROR`,
};
export default constants;
