const constants = {
    SIGNUP_START: "SIGNUP_START",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_ERROR: "SIGNUP_ERROR",

    SIGNIN_START: "SIGNIN_START",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_ERROR: "SIGNIN_ERROR",

    SEND_RESET_PASSWORD_START : "SEND_RESET_PASSWORD_START",
    SEND_RESET_PASSWORD_SUCCESS : "SEND_RESET_PASSWORD_SUCCESS",
    SEND_RESET_PASSWORD_ERROR : "SEND_RESET_PASSWORD_ERROR",

    CHANGE_PASSWORD_START : "CHANGE_PASSWORD_START",
    CHANGE_PASSWORD_SUCCESS : "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_ERROR : "CHANGE_PASSWORD_ERROR",
};

export default constants;
